In [3]:
import numpy as np
import pandas as pd

# LPG 데이터 프레임 만들기

In [450]:
# DB로 만들 LPG_DATAFRAME만들기. 
lpg_dataframe = pd.DataFrame(columns=['lpg_id', 'name', 'x_cor', 'y_cor', 'installed_2020', 'installed_2022', 'installed_2024', 'installed_2026', 'installed_2028', 'dong_id', '동'])

In [451]:
# lpg 전체 데이터를 불러온다. 
lpg = pd.read_csv("raw_Data/lpg.csv", encoding='cp949')

In [452]:
# 겹치는 것은 뺀다. 
lpg = lpg.drop_duplicates(subset='업체명')

In [453]:
# 이름 데이터를 뺸다. 
lpg_name = lpg['업체명']

In [454]:
# 경도 데이터를 뺀다. 
lpg_x_cor = lpg['경도']

In [455]:
# 위도 데이터를 뺀다. 
lpg_y_cor = lpg['위도']

In [456]:
# 동 데이터를 뺸다. 
lpg_dong = lpg['동']

In [457]:
# 자치구 데이터를 뺀다 .
lpg_gu = lpg['자치구']

In [458]:
# 이름 데이터 넣기.
lpg_dataframe['name'] = lpg_name

In [459]:
# lpg_id 넣기.
lpg_dataframe['lpg_id'] = list(range(0,len(lpg_dataframe)))

In [460]:
# x_cor넣기.
lpg_dataframe['x_cor'] = lpg_x_cor

In [461]:
# y_cor넣기.
lpg_dataframe['y_cor'] = lpg_y_cor

In [462]:
# 동 넣기.
lpg_dataframe['동'] = lpg_dong

In [463]:
lpg_dataframe['자치구'] = lpg_gu

In [464]:
# 2020, 2022, 2024, 2026, 2028 다 0으로 채우기.
for year in [2020, 2022, 2024, 2026, 2028]:
    lpg_dataframe["installed_" + str(year)] = 0

# 주차장 데이터 프레임 만들기.

In [4]:
pl_dataframe = pd.DataFrame(columns=['pl_id', 'name', 'x_cor', 'y_cor', 'installed_2020', 'installed_2022', 'installed_2024', 'installed_2026', 'installed_2028', 'dong_id', '동'])

In [5]:
# 기존 데이터에서 가져온다. 
temp = pd.read_csv("raw_Data/1600_hy_1.csv", encoding='cp949')

In [6]:
# parking_lot 정보만 가져온다. 
parking_lot=temp[[ '자치구', '동', '주차장명', '주차장구분',
       '주차장유형', '주차구획수', '주차급지구분', '주차부제시행구분', '주차운영요일', '평일운영시작시각',
       '평일운영종료시각', '토요일운영시작시각', '토요일운영종료시각', '주차요금정보', '주차기본시간', '주차기본요금',
       '주차경도', '주차위도']]

In [7]:
# 필요없는 애들은 drop한다. 
parking_lot.dropna(inplace=True)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
# 총 363개가 있다. 
len(parking_lot)

363

In [9]:
# 이름을 저장한다. 
parking_lot_name = parking_lot['주차장명']

In [17]:
parking_lot.groupby('동').count()[parking_lot.groupby('동').count()['주차장명'] > 3]

,자치구,주차장명,주차장구분,주차장유형,주차구획수,주차급지구분,주차부제시행구분,주차운영요일,평일운영시작시각,평일운영종료시각,토요일운영시작시각,토요일운영종료시각,주차요금정보,주차기본시간,주차기본요금,주차경도,주차위도
동,,,,,,,,,,,,,,,,,
당산1동,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
명동,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
목5동,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
방화2동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
삼성1동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
삼양동,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
소공동,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
수유1동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
신사동,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
양재2동,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
을지로동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
일원1동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
일원2동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
잠실6동,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
천호2동,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4

In [381]:
# 경도를 저장한다. 
parking_lot_x_cor = parking_lot['주차위도']

In [382]:
# 위도를 저장한다. 
parking_lot_y_cor = parking_lot['주차경도']

In [383]:
# 동을 저장한다. 
parking_dong = parking_lot['동']

In [384]:
# 자치구를 저장한다. 
parking_gu = parking_lot['자치구']

In [385]:
# 아이디를 넣는다. 
pl_dataframe['pl_id'] = list(range(0, len(pl_dataframe)))

In [386]:
# 이름을 넣는다. 
pl_dataframe['name'] = parking_lot_name

In [387]:
# 경도를 넣는다. 
pl_dataframe['x_cor'] = parking_lot_x_cor

In [388]:
# 위도를 넣는다. 
pl_dataframe['y_cor'] = parking_lot_y_cor

In [389]:
for year in [2020, 2022, 2024, 2026, 2028]:
    pl_dataframe['installed_' + str(year)] = 0

In [390]:
# 동데이터를 넣는다 .
pl_dataframe['동'] = parking_dong

In [391]:
# 구 데이터를 넣는다. 
pl_dataframe['자치구'] = parking_gu

In [396]:
# pl_id 넣기.
pl_dataframe['pl_id'] = list(range(0,len(pl_dataframe)))

# 2022년 데이터를 LPG와 주차장에 넣기.

In [465]:
# 2020년 LPG충전소와 주차장 LIST 가져오기. 
year_2022_list = pd.read_csv("년도별_후보지_리스트/final_list_2.csv", encoding='cp949')

### 2020년 주유소 넣기.

In [466]:
# 2022_list에서 주유소 이름만 빼기. 
station_name_2022 = year_2022_list['업체명']

In [467]:
# 2022년 데이터에 넣기.
for name in station_name_2022:
    if not pd.isna(name):
        index = lpg_dataframe[lpg_dataframe['name'] == name].index[0]
        lpg_dataframe.loc[index, 'installed_2022'] = 1

### 2022년 주차장 넣기.

In [392]:
# 2022_list에서 주자창 이름만 빼기. 
pl_name_2022 = list(year_2022_list['주차장명'])

In [393]:
pl_name_2022

[nan,
 nan,
 '역삼문화공원',
 '일원터널',
 '천호역',
 '공항동(송정역)',
 '화곡5-2',
 '대방생태',
 '잠원동 방음언덕형 공영주차장',
 '당산2동 공영주차장']

In [394]:
# 2024년 데이터 넣기.
for name in pl_name_2022:
    if not pd.isna(name):
        index = pl_dataframe[pl_dataframe['name'] == name].index[0]
        pl_dataframe.loc[index, 'installed_2022'] = 1

In [397]:
pl_dataframe[pl_dataframe['installed_2022'] == 1]

,pl_id,name,x_cor,y_cor,installed_2020,installed_2022,installed_2024,installed_2026,installed_2028,dong_id,동,자치구
18,16,역삼문화공원,37.502514,127.030390,0,1,0,0,0,NaN,역삼1동,강남구
28,26,일원터널,37.482745,127.078902,0,1,0,0,0,NaN,일원본동,강남구
62,51,천호역,37.538507,127.125128,0,1,0,0,0,NaN,천호2동,강동구
112,88,공항동(송정역),37.560321,126.810614,0,1,0,0,0,NaN,공항동,강서구
124,99,화곡5-2,37.544177,126.838548,0,1,0,0,0,NaN,우장산동,강서구
260,163,대방생태,37.500189,126.926641,0,1,0,0,0,NaN,대방동,동작구
304,176,잠원동 방음언덕형 공영주차장,37.515762,127.016135,0,1,0,0,0,NaN,잠원동,서초구
455,283,당산2동 공영주차장,37.528213,126.907776,0,1,0,0,0,NaN,당산2동,영등포구

# 2024년 데이터를 LPG와 주차장에 넣기.

In [468]:
# 2024년 리스트 데이터 가져오기.
year_2024_list = pd.read_csv("년도별_후보지_리스트/final_list_16.csv", encoding='cp949')

### 2024년 주유소 넣기.

In [469]:
# 2024_list에서 주유소 이름만 빼기. 
station_name_2024 = year_2024_list['업체명']

In [470]:
station_name_2024

0            (주)상현상사
1           남서울가스(주)
2            강남복지충전소
3              둔촌충전소
4           대영가스 충전소
5            강서가스충전소
6         대흥에너지산업(주)
7       동일석유(주)남부충전소
8       수도석유(주)방배충전소
9       동일석유(주)동주충전소
10           (주)영동가스
11             서초충전소
12           오금가스충전소
13             (주)세지
14    (주)삼표에너지 수색충전소
15           은평서부충전소
16               NaN
17               NaN
18               NaN
19               NaN
20               NaN
21               NaN
22               NaN
23               NaN
24               NaN
25               NaN
26               NaN
27               NaN
28               NaN
29               NaN
           ...
50               NaN
51               NaN
52               NaN
53               NaN
54               NaN
55               NaN
56               NaN
57               NaN
58               NaN
59               NaN
60               NaN
61               NaN
62               NaN
63               NaN
64               NaN
65               NaN
66               NaN
67               NaN
68               NaN
69               NaN
70               NaN
71               NaN
72               NaN
73               NaN
74               NaN
75               NaN
76               NaN
77               NaN
78               NaN
79               NaN
Name: 업체명, Length: 80, dtype: object

In [471]:
# 2024년 데이터에 넣기.
for name in station_name_2024:
    if not pd.isna(name):
        index = lpg_dataframe[lpg_dataframe['name'] == name].index[0]
        lpg_dataframe.loc[index, 'installed_2024'] = 1

### 2024년 주차장 넣기.

In [398]:
# 2024_list에서 주자창 이름만 빼기. 
pl_name_2024 = list(year_2024_list['주차장명'])

In [399]:
pl_name_2024

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '탄천주차장',
 '삼성로별관 부설',
 '도곡로21길7',
 '역삼문화공원',
 '도곡로327',
 '구룡산제2호',
 '개포로24길33',
 '일원역',
 '일원터널',
 '수서역',
 '언북초교',
 '개포동공원',
 '암사1동공영주차장',
 '화곡본-2',
 '화곡6-1',
 '화곡5-2',
 '천왕역',
 '하늘공원 주차장',
 '가산동',
 '독산1동',
 '도화',
 '신대방역',
 '흑석3동',
 '동작대교',
 '미근동',
 '교대역동측',
 '언구비 주차빌딩',
 '미도아파트 앞 주차빌딩',
 '반포4동 주민센터 공영주차장',
 '이수 주차빌딩',
 '사당노외',
 '방배열린 문화센터',
 '양재주차빌딩',
 '청계산청룡',
 '방이동',
 '가락동2(체비지)',
 '문정근린공원',
 '아시아공원',
 '더다이닝호수',
 '서울놀이마당',
 '달마을',
 '목3동 해운',
 '다락골',
 '어울림',
 '밝은빛',
 '목동타운홀',
 '양평2동청사 공영주차장',
 '당산1동 공영주차장',
 '신길1동공영주차장',
 '신길6동공영주차장',
 '대림3동공영주차장',
 '대림운동장공영주차장',
 '영등포본동제1 공영주차장',
 '영등포동제2 공영주차장',
 '신길환승(5호선)공영주차장',
 '갈현1동 공영주차장',
 '서신초교지하공영주차장',
 '새장골 공영주차장',
 '응암3동 공영주차장',
 '매바위공영주차장',
 '비봉',
 '종묘',
 '서인사마당',
 '신당동 공영주차장']

In [400]:
# 2024년 데이터 넣기.
for name in pl_name_2024:
    if not pd.isna(name):
        index = pl_dataframe[pl_dataframe['name'] == name].index[0]
        pl_dataframe.loc[index, 'installed_2024'] = 1

# 2026년 데이터를 LPG와 주차장에 넣기.

In [472]:
# 2026년 리스트 데이터 가져오기.
year_2026_list = pd.read_csv("년도별_후보지_리스트/final_list_43.csv", encoding='cp949')

### 2026년 주유소 넣기.

In [473]:
# 2026_list에서 주유소 이름만 빼기. 
station_name_2026 = year_2026_list['업체명']

In [474]:
station_name_2026

0               (주)상현상사
1                  진양가스
2              남서울가스(주)
3              (주)수서에너지
4               복지상일충전소
5              (주)경기에너지
6                 둔촌충전소
7             서울와사공업(주)
8              (주)청학에너지
9               복지마곡충전소
10              대양가스충전소
11       (주)삼표에너지 김포충전소
12     (주)에너지플러스 오곡동충전소
13           대흥에너지산업(주)
14              명화가스(주)
15                신림충전소
16         동일석유(주)남부충전소
17           오승프라임산업(주)
18            한일가스산업(주)
19                개봉충전소
20       수도에너지(주)동서울충전소
21           (주)홍릉가스충전소
22              복지장안충전소
23             장안동가스충전소
24         수도석유(주)방배충전소
25         동일석유(주)동주충전소
26            연일가스산업(주)
27              (주)영동가스
28                서초충전소
29              덕마가스충전소
             ...
185                 NaN
186                 NaN
187                 NaN
188                 NaN
189                 NaN
190                 NaN
191                 NaN
192                 NaN
193                 NaN
194                 NaN
195                 NaN
196                 NaN
197                 NaN
198                 NaN
199                 NaN
200                 NaN
201                 NaN
202                 NaN
203                 NaN
204                 NaN
205                 NaN
206                 NaN
207                 NaN
208                 NaN
209                 NaN
210                 NaN
211                 NaN
212                 NaN
213                 NaN
214                 NaN
Name: 업체명, Length: 215, dtype: object

In [475]:
# 2026년 데이터에 넣기.
for name in station_name_2026:
    if not pd.isna(name):
        index = lpg_dataframe[lpg_dataframe['name'] == name].index[0]
        lpg_dataframe.loc[index, 'installed_2026'] = 1

### 2026년 주차장 넣기.

In [401]:
# 2026_list에서 주자창 이름만 빼기. 
pl_name_2026 = list(year_2026_list['주차장명'])

In [402]:
# 2026년 데이터 넣기.
for name in pl_name_2026:
    if not pd.isna(name):
        index = pl_dataframe[pl_dataframe['name'] == name].index[0]
        pl_dataframe.loc[index, 'installed_2026'] = 1

# 2028년 데이터를 LPG와 주차장에 넣기.

In [476]:
# 2028년 리스트 데이터 가져오기.
year_2028_list = pd.read_csv("년도별_후보지_리스트/final_list_68.csv", encoding='cp949')

### 2028년 주유소 넣기.

In [477]:
# 2028_list에서 주유소 이름만 빼기. 
station_name_2028 = year_2028_list['업체명']

In [478]:
# 2028년 데이터에 넣기.
for name in station_name_2028:
    if not pd.isna(name):
        index = lpg_dataframe[lpg_dataframe['name'] == name].index[0]
        lpg_dataframe.loc[index, 'installed_2028'] = 1

### 2028년 주차장 넣기.

In [403]:
# 2028_list에서 주자창 이름만 빼기. 
pl_name_2028 = list(year_2028_list['주차장명'])

In [404]:
# 2028년 데이터 넣기.
for name in pl_name_2028:
    if not pd.isna(name):
        index = pl_dataframe[pl_dataframe['name'] == name].index[0]
        pl_dataframe.loc[index, 'installed_2028'] = 1

# 잘 들어갔는지 체크하기.

In [479]:
lpg_dataframe

,lpg_id,name,x_cor,y_cor,installed_2020,installed_2022,installed_2024,installed_2026,installed_2028,dong_id,동,자치구
0,0,덕마가스충전소,37.548711,127.042727,0,0,0,1,1,NaN,성수1가2동,성동구
1,1,대성산업(주)동부충전소,37.550454,127.050193,0,0,0,0,1,NaN,성수2가3동,성동구
2,2,현대오일뱅크 중곡동충전소,37.560049,127.071521,0,0,0,0,1,NaN,중곡1동,광진구
3,3,한양에너지(주),37.564958,127.074351,0,0,0,0,1,NaN,중곡1동,광진구
4,4,해양가스,37.534588,127.081491,0,0,0,0,1,NaN,자양1동,광진구
5,5,수도에너지(주)동서울충전소,37.589635,127.057249,0,0,0,1,1,NaN,휘경1동,동대문구
6,6,(주)홍릉가스충전소,37.591046,127.039042,0,0,0,1,1,NaN,청량리동,동대문구
7,7,복지장안충전소,37.576154,127.065037,0,0,0,1,1,NaN,답십리2동,동대문구
8,8,장안동가스충전소,37.562897,127.056468,0,0,0,1,1,NaN,장안1동,동대문구
9,9,(주)풍림에너지,37.579640,127.077050,0,0,0,1,1,NaN,면목5동,중랑구
10,10,동일석유(주)황금충전소,37.594147,127.073658,0,0,0,1,1,NaN,중화2동,중랑구
11,11,신내LPG충전소,37.612708,127.098625,0,0,0,1,1,NaN,신내1동,중랑구
12,12,망우충전소,37.600566,127.099727,0,0,0,0,1,NaN,망우본동,중랑구
13,13,우일에너지(주),37.607911,127.028059,0,0,0,1,1,NaN,길음2동,성북구
14,14,(주)장위가스,37.613232,127.058435,0,0,0,1,1,NaN,장위3동,성북구
15,15,서울와사공업(주),37.636198,127.022329,0,0,0,1,1,NaN,번1동,강북구
16,16,(주)청학에너지,37.628133,127.041865,0,0,0,1,1,NaN,번3동,강북구
17,17,국제가스공업(주),37.634290,127.019657,0,0,0,0,1,NaN,수유1동,강북구
21,18,케이와이에너지 (주)한영충전소,37.660563,127.039175,0,0,0,0,1,NaN,쌍문2동,도봉구
22,19,(주)에스케이행복에너지,37.665771,127.041380,0,0,0,0,1,NaN,방학1동,도봉구
23,20,동원가스충전소,37.644256,127.030357,0,0,0,0,1,NaN,창2동,도봉구
24,21,(주)평안에너지 도봉충전소,37.666950,127.003720,0,0,0,0,1,NaN,도봉1동,도봉구
25,22,복지공릉충전소,37.638797,127.107360,0,0,0,0,0,NaN,공릉2동,노원구
26,23,(주)노일가스,37.671412,127.053361,0,0,0,0,1,NaN,상계1동,노원구
27,24,복지노원충전소,37.686866,127.053645,0,0,0,0,1,NaN,상계1동,노원구
28,25,(주)평안에너지상계충전소,37.649171,127.064857,0,0,0,0,0,NaN,중계2.3동,노원구
29,26,신성에너지주식회사,37.629062,127.068660,0,0,0,0,1,NaN,공릉1동,노원구
30,27,태능가스(주),37.616956,127.070336,0,0,0,0,1,NaN,공릉1동,노원구
31,28,신흥에너지산업(주),37.578588,126.898188,0,0,0,0,1,NaN,증산동,은평구
32,29,(주)삼표에너지 수색충전소,37.577704,126.899168,0,0,1,0,0,NaN,증산동,은평구
...,...,...,...,...,...,...,...,...,...,...,...,...
59,47,대흥에너지산업(주),37.529724,126.845029,0,1,1,1,1,NaN,화곡1동,강서구
60,48,동일석유(주)남부충전소,37.484273,126.899764,0,0,1,1,1,NaN,구로3동,구로구
62,49,대성산업(주)오류동충전소,37.538042,126.728050,0,0,0,0,0,NaN,오류2동,구로구
63,50,오승프라임산업(주),37.506903,126.826906,0,0,0,1,1,NaN,수궁동,구로구
64,51,한일가스산업(주),37.501882,126.875666,0,0,0,1,1,NaN,구로2동,구로구
65,52,개봉충전소,37.496421,126.858357,0,0,0,1,1,NaN,개봉1동,구로구
68,53,(주)중앙에너비스 삼중가스지점,37.461797,126.896135,0,0,0,0,1,NaN,독산2동,금천구
69,54,양평동충전소,37.527936,126.888910,0,0,0,0,1,NaN,양평1동,영등포구
70,55,기린에너지,37.536256,126.896764,0,0,0,1,1,NaN,양평2동,영등포구
71,56,(주)세지,37.517433,126.886258,0,0,1,1,1,NaN,문래동,영등포구
73,57,수도석유(주)방배충전소,37.486896,126.973018,0,0,1,1,1,NaN,사당1동,동작구
74,58,동일석유(주)동주충전소,37.499417,126.926646,0,0,1,1,1,NaN,대방동,동작구
75,59,명화가스(주),37.473676,126.951276,0,0,0,1,1,NaN,낙성대동,관악구
76,60,신림충전소,37.473539,126.931969,0,0,0,1,1,NaN,서림동,관악구
77,61,(주)영동가스,37.518893,127.009666,0,0,1,1,1,NaN,잠원동,서초구
78,62,서초충전소,37.473066,126.993278,0,0,1,1,1,NaN,방배3동,서초구
79,63,(주)에이치앤디이-서울만남의광장,37.459906,127.039871,0,0,0,0,0,NaN,양재2동,서초구
86,64,(주)상현상사,37.513631,127.029157,0,0,1,1,1,NaN,논현2동,강남구
87,65,진양가스,37.490583,127.034634,0,0,0,1,1,NaN,도곡1동,강남구
88,66,대치에너지주식회사,37.499300,127.075901,0,0,0,0,1,NaN,일원2동,강남구
90,67,남서울가스(주),37.497780,127.073376,0,0,1,1,1,NaN,일원2동,강남구
92,68,강남복지충전소,37.476329,127.103276,0,1,1,0,1,NaN,세곡동,강남구
93,69,(주)수서에너지,37.482796,127.102826,0,0,0,1,1,NaN,세곡동,강남구
94,70,오금가스충전소,37.506158,127.129408,0,0,1,1,1,NaN,오금동,송파구
95,71,홍익에너지(주),37.508105,127.101451,0,0,0,1,1,NaN,석촌동,송파구
96,72,강동LPG충전소,37.503449,127.084675,0,0,0,0,1,NaN,잠실본동,송파구
97,73,복지상일충전소,37.545049,127.167585,0,0,0,1,1,NaN,상일동,강동구
98,74,암사충전소,37.551779,127.125545,0,0,0,0,1,NaN,암사2동,강동구
99,75,(주)경기에너지,37.536485,127.126803,0,0,0,1,1,NaN,성내2동,강동구
100,76,둔촌충전소,37.525233,127.144409,0,0,1,1,1,NaN,둔촌2동,강동구

In [405]:
pl_dataframe

,pl_id,name,x_cor,y_cor,installed_2020,installed_2022,installed_2024,installed_2026,installed_2028,dong_id,동,자치구
0,0,남부초공영주차장,37.485041,126.922117,0,0,0,1,1,NaN,신사동,강남구
1,1,신사동제1공영주차장,37.484397,126.915444,0,0,0,1,1,NaN,신사동,강남구
2,2,압구정428,37.526842,127.027056,0,0,0,1,1,NaN,신사동,강남구
3,3,신구초교,37.523361,127.023992,0,0,0,1,1,NaN,신사동,강남구
4,4,논현초교,37.508491,127.026222,0,0,0,1,1,NaN,논현1동,강남구
6,5,삼성1동문화센터,37.514355,127.062609,0,0,0,1,1,NaN,삼성1동,강남구
7,6,탄천주차장,37.514112,127.066491,0,0,1,1,1,NaN,삼성1동,강남구
8,7,삼성로별관 부설,37.515910,127.052141,0,0,1,1,1,NaN,삼성1동,강남구
9,8,탄천,37.512890,127.069268,0,0,0,0,1,NaN,삼성1동,강남구
10,9,강남치매지원센터,37.510312,127.046378,0,0,0,1,1,NaN,삼성2동,강남구
11,10,구청 부설,37.517966,127.047061,0,0,0,0,1,NaN,삼성2동,강남구
13,11,도산대로25길32,37.497679,127.056453,0,0,0,0,0,NaN,대치4동,강남구
14,12,도곡로421,37.497679,127.056453,0,0,0,1,1,NaN,대치4동,강남구
15,13,도곡초교,37.499511,127.054464,0,0,0,0,1,NaN,대치4동,강남구
16,14,도곡로21길7,37.492593,127.038872,0,0,1,1,1,NaN,역삼1동,강남구
17,15,역삼1동문화센터,37.495374,127.033282,0,0,0,1,1,NaN,역삼1동,강남구
18,16,역삼문화공원,37.502514,127.030390,0,1,1,1,1,NaN,역삼1동,강남구
19,17,도곡로327,37.496157,127.051666,0,0,1,1,1,NaN,역삼2동,강남구
20,18,언주초교,37.486323,127.036793,0,0,0,0,0,NaN,도곡1동,강남구
21,19,논현로32길15,37.484252,127.043440,0,0,0,1,1,NaN,도곡2동,강남구
22,20,구룡산제1호,37.476067,127.067285,0,0,0,1,0,NaN,개포1동,강남구
23,21,구룡산제2호,37.476067,127.067285,0,0,1,0,1,NaN,개포1동,강남구
24,22,포이초교,37.475293,127.051416,0,0,0,0,1,NaN,개포4동,강남구
25,23,논현로22길,37.481259,127.046816,0,0,0,0,1,NaN,개포4동,강남구
26,24,개포로24길33,37.477139,127.049749,0,0,1,1,1,NaN,개포4동,강남구
27,25,일원역,37.484669,127.084056,0,0,1,1,1,NaN,일원본동,강남구
28,26,일원터널,37.482745,127.078902,0,1,1,1,1,NaN,일원본동,강남구
29,27,탄천제2호,37.493147,127.087768,0,0,0,1,1,NaN,일원1동,강남구
30,28,일원1동,37.489566,127.081793,0,0,0,1,1,NaN,일원1동,강남구
31,29,영희초교,37.492302,127.081131,0,0,0,0,1,NaN,일원1동,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...
546,333,약수동 공영주차장,37.567925,126.979982,0,0,0,0,1,NaN,명동,중구
547,334,필동 공영주차장,37.568355,126.977748,0,0,0,0,1,NaN,명동,중구
548,335,서소문삼성생명뒤 공영주차장,37.567361,126.989609,0,0,0,1,1,NaN,명동,중구
549,336,남산동 공영주차장,37.567876,126.981139,0,0,0,0,1,NaN,명동,중구
552,337,신당사거리 공영주차장,37.565313,126.995967,0,0,0,1,1,NaN,광희동,중구
553,338,신당역 공영주차장,37.563702,126.996663,0,0,0,0,1,NaN,광희동,중구
554,339,훈련원 화물대기,37.567026,127.003609,0,0,0,1,1,NaN,을지로동,중구
555,340,버티 공영주차장,37.567613,126.995732,0,0,0,0,1,NaN,을지로동,중구
556,341,중구구민회관 부설주차장,37.567643,127.005018,0,0,0,0,1,NaN,을지로동,중구
557,342,중림종합복지센터 부설주차장,37.567677,126.994011,0,0,0,0,1,NaN,을지로동,중구
558,343,충현어린이공원 공영주차장,37.565054,127.022888,0,0,0,1,1,NaN,신당5동,중구
560,344,충현 공영주차장,37.559548,126.966218,0,0,0,1,1,NaN,중림동,중구
561,345,다산아트 공영주차장,37.567444,127.016776,0,0,0,1,1,NaN,신당동,중구
562,346,신당동 공영주차장,37.562026,127.014296,0,0,1,1,1,NaN,신당동,중구
567,347,중랑초교,37.589184,127.075783,0,0,0,1,1,NaN,면목2동,중랑구
568,348,면목2동,37.587934,127.080895,0,0,0,1,1,NaN,면목2동,중랑구
569,349,중곡초교,37.574760,127.082679,0,0,0,1,1,NaN,면목4동,중랑구
570,350,용마폭포,37.573354,127.089120,0,0,0,1,1,NaN,면목4동,중랑구
571,351,면목5동,37.582961,127.080061,0,0,0,0,0,NaN,면목5동,중랑구
574,352,상봉2동,37.593049,127.084325,0,0,0,1,1,NaN,상봉2동,중랑구
575,353,중화1동,37.602749,127.081659,0,0,0,1,1,NaN,중화1동,중랑구
577,354,화랑대역,37.620090,127.086690,0,0,0,1,1,NaN,묵1동,중랑구
579,355,면일초교,37.591981,127.099374,0,0,0,0,1,NaN,망우3동,중랑구
581,356,봉화산역(남),37.616427,127.091907,0,0,0,1,1,NaN,신내2동,중랑구
582,357,봉수대,37.607077,127.092622,0,0,0,1,1,NaN,신내2동,중랑구
583,358,동원시장,37.590016,127.091944,0,0,0,1,1,NaN,면목본동,중랑구
584,359,은행나무,37.587058,127.091578,0,0,0,0,1,NaN,면목본동,중랑구
585,360,늘봄,37.589818,127.096400,0,0,0,1,1,NaN,면목3.8동,중랑구
586,361,까치공원,37.583508,127.086968,0,0,0,1,1,NaN,면목3.8동,중랑구
587,362,금란,37.599869,127.101590,0,0,0,1,0,NaN,망우본동,중랑구

# dong_id 넣기.

In [439]:
dong_dataframe = pd.read_csv("DB_Data/DONG.csv")

In [440]:
len(dong_dataframe)

424

In [441]:
dong_dataframe[dong_dataframe['동'] == '신사동']

,index,DONG_ID,자치구,동,2020_rate,2022_rate,2024_rate,2026_rate,2028_rate
0,1,1,강남구,신사동,2.95702,2.95702,2.95702,2.95702,2.95702
83,84,84,관악구,신사동,1.71705,1.71705,1.71705,1.71705,1.71705

In [442]:
dong_temp = pd.DataFrame(columns=['dong_id', '동', '자치구'])

In [443]:
dong_temp['dong_id'] = dong_dataframe['DONG_ID']

In [444]:
dong_temp['자치구'] = dong_dataframe['자치구']

In [445]:
dong_temp['동'] = dong_dataframe['동']

In [449]:
dong_temp[dong_id] == 2

     dong_id       동  자치구
0          1     신사동  강남구
1          2    논현1동  강남구
2          3    논현2동  강남구
3          4    삼성1동  강남구
4          5    삼성2동  강남구
5          6    대치1동  강남구
6          7    대치4동  강남구
7          8    역삼1동  강남구
8          9    역삼2동  강남구
9         10    도곡1동  강남구
10        11    도곡2동  강남구
11        12    개포1동  강남구
12        13    개포4동  강남구
13        14    일원본동  강남구
14        15    일원1동  강남구
15        16    일원2동  강남구
16        17     수서동  강남구
17        18     세곡동  강남구
18        19    압구정동  강남구
19        20     청담동  강남구
20        21    대치2동  강남구
21        22    개포2동  강남구
22        23     강일동  강동구
23        24     상일동  강동구
24        25    명일1동  강동구
25        26    명일2동  강동구
26        27    고덕1동  강동구
27        28    고덕2동  강동구
28        29    암사2동  강동구
29        30    암사3동  강동구
..       ...     ...  ...
394      395     회현동   중구
395      396      명동   중구
396      397      필동   중구
397      398     장충동   중구
398      399     광희동   중구
399      400    을지로동   중구
400      401    신당5동   중구
401      402     황학동   중구
402      403     중림동   중구
403      404     신당동   중구
404      405     다산동   중구
405      406     약수동   중구
406      407     청구동   중구
407      408     동화동   중구
408      409    면목2동  중랑구
409      410    면목4동  중랑구
410      411    면목5동  중랑구
411      412    면목7동  중랑구
412      413    상봉1동  중랑구
413      414    상봉2동  중랑구
414      415    중화1동  중랑구
415      416    중화2동  중랑구
416      417     묵1동  중랑구
417      418     묵2동  중랑구
418      419    망우3동  중랑구
419      420    신내1동  중랑구
420      421    신내2동  중랑구
421      422    면목본동  중랑구
422      423  면목3.8동  중랑구
423      424    망우본동  중랑구

[424 rows x 3 columns]

### lpg dataframe에 넣기.

In [481]:
lpg_dataframe = pd.merge(lpg_dataframe, dong_temp, how='left', on = ['동', '자치구'])

In [482]:
lpg_dataframe

,lpg_id,name,x_cor,y_cor,installed_2020,installed_2022,installed_2024,installed_2026,installed_2028,dong_id_x,동,자치구,dong_id_y
0,0,덕마가스충전소,37.548711,127.042727,0,0,0,1,1,NaN,성수1가2동,성동구,254
1,1,대성산업(주)동부충전소,37.550454,127.050193,0,0,0,0,1,NaN,성수2가3동,성동구,256
2,2,현대오일뱅크 중곡동충전소,37.560049,127.071521,0,0,0,0,1,NaN,중곡1동,광진구,97
3,3,한양에너지(주),37.564958,127.074351,0,0,0,0,1,NaN,중곡1동,광진구,97
4,4,해양가스,37.534588,127.081491,0,0,0,0,1,NaN,자양1동,광진구,106
5,5,수도에너지(주)동서울충전소,37.589635,127.057249,0,0,0,1,1,NaN,휘경1동,동대문구,169
6,6,(주)홍릉가스충전소,37.591046,127.039042,0,0,0,1,1,NaN,청량리동,동대문구,171
7,7,복지장안충전소,37.576154,127.065037,0,0,0,1,1,NaN,답십리2동,동대문구,177
8,8,장안동가스충전소,37.562897,127.056468,0,0,0,1,1,NaN,장안1동,동대문구,178
9,9,(주)풍림에너지,37.579640,127.077050,0,0,0,1,1,NaN,면목5동,중랑구,411
10,10,동일석유(주)황금충전소,37.594147,127.073658,0,0,0,1,1,NaN,중화2동,중랑구,416
11,11,신내LPG충전소,37.612708,127.098625,0,0,0,1,1,NaN,신내1동,중랑구,420
12,12,망우충전소,37.600566,127.099727,0,0,0,0,1,NaN,망우본동,중랑구,424
13,13,우일에너지(주),37.607911,127.028059,0,0,0,1,1,NaN,길음2동,성북구,271
14,14,(주)장위가스,37.613232,127.058435,0,0,0,1,1,NaN,장위3동,성북구,276
15,15,서울와사공업(주),37.636198,127.022329,0,0,0,1,1,NaN,번1동,강북구,41
16,16,(주)청학에너지,37.628133,127.041865,0,0,0,1,1,NaN,번3동,강북구,43
17,17,국제가스공업(주),37.634290,127.019657,0,0,0,0,1,NaN,수유1동,강북구,44
18,18,케이와이에너지 (주)한영충전소,37.660563,127.039175,0,0,0,0,1,NaN,쌍문2동,도봉구,155
19,19,(주)에스케이행복에너지,37.665771,127.041380,0,0,0,0,1,NaN,방학1동,도봉구,158
20,20,동원가스충전소,37.644256,127.030357,0,0,0,0,1,NaN,창2동,도봉구,162
21,21,(주)평안에너지 도봉충전소,37.666950,127.003720,0,0,0,0,1,NaN,도봉1동,도봉구,166
22,22,복지공릉충전소,37.638797,127.107360,0,0,0,0,0,NaN,공릉2동,노원구,138
23,23,(주)노일가스,37.671412,127.053361,0,0,0,0,1,NaN,상계1동,노원구,144
24,24,복지노원충전소,37.686866,127.053645,0,0,0,0,1,NaN,상계1동,노원구,144
25,25,(주)평안에너지상계충전소,37.649171,127.064857,0,0,0,0,0,NaN,중계2.3동,노원구,152
26,26,신성에너지주식회사,37.629062,127.068660,0,0,0,0,1,NaN,공릉1동,노원구,153
27,27,태능가스(주),37.616956,127.070336,0,0,0,0,1,NaN,공릉1동,노원구,153
28,28,신흥에너지산업(주),37.578588,126.898188,0,0,0,0,1,NaN,증산동,은평구,371
29,29,(주)삼표에너지 수색충전소,37.577704,126.899168,0,0,1,0,0,NaN,증산동,은평구,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,47,대흥에너지산업(주),37.529724,126.845029,0,1,1,1,1,NaN,화곡1동,강서구,72
48,48,동일석유(주)남부충전소,37.484273,126.899764,0,0,1,1,1,NaN,구로3동,구로구,112
49,49,대성산업(주)오류동충전소,37.538042,126.728050,0,0,0,0,0,NaN,오류2동,구로구,120
50,50,오승프라임산업(주),37.506903,126.826906,0,0,0,1,1,NaN,수궁동,구로구,121
51,51,한일가스산업(주),37.501882,126.875666,0,0,0,1,1,NaN,구로2동,구로구,123
52,52,개봉충전소,37.496421,126.858357,0,0,0,1,1,NaN,개봉1동,구로구,124
53,53,(주)중앙에너비스 삼중가스지점,37.461797,126.896135,0,0,0,0,1,NaN,독산2동,금천구,127
54,54,양평동충전소,37.527936,126.888910,0,0,0,0,1,NaN,양평1동,영등포구,330
55,55,기린에너지,37.536256,126.896764,0,0,0,1,1,NaN,양평2동,영등포구,331
56,56,(주)세지,37.517433,126.886258,0,0,1,1,1,NaN,문래동,영등포구,344
57,57,수도석유(주)방배충전소,37.486896,126.973018,0,0,1,1,1,NaN,사당1동,동작구,187
58,58,동일석유(주)동주충전소,37.499417,126.926646,0,0,1,1,1,NaN,대방동,동작구,191
59,59,명화가스(주),37.473676,126.951276,0,0,0,1,1,NaN,낙성대동,관악구,77
60,60,신림충전소,37.473539,126.931969,0,0,0,1,1,NaN,서림동,관악구,83
61,61,(주)영동가스,37.518893,127.009666,0,0,1,1,1,NaN,잠원동,서초구,231
62,62,서초충전소,37.473066,126.993278,0,0,1,1,1,NaN,방배3동,서초구,240
63,63,(주)에이치앤디이-서울만남의광장,37.459906,127.039871,0,0,0,0,0,NaN,양재2동,서초구,243
64,64,(주)상현상사,37.513631,127.029157,0,0,1,1,1,NaN,논현2동,강남구,3
65,65,진양가스,37.490583,127.034634,0,0,0,1,1,NaN,도곡1동,강남구,10
66,66,대치에너지주식회사,37.499300,127.075901,0,0,0,0,1,NaN,일원2동,강남구,16
67,67,남서울가스(주),37.497780,127.073376,0,0,1,1,1,NaN,일원2동,강남구,16
68,68,강남복지충전소,37.476329,127.103276,0,1,1,0,1,NaN,세곡동,강남구,18
69,69,(주)수서에너지,37.482796,127.102826,0,0,0,1,1,NaN,세곡동,강남구,18
70,70,오금가스충전소,37.506158,127.129408,0,0,1,1,1,NaN,오금동,송파구,291
71,71,홍익에너지(주),37.508105,127.101451,0,0,0,1,1,NaN,석촌동,송파구,294
72,72,강동LPG충전소,37.503449,127.084675,0,0,0,0,1,NaN,잠실본동,송파구,303
73,73,복지상일충전소,37.545049,127.167585,0,0,0,1,1,NaN,상일동,강동구,24
74,74,암사충전소,37.551779,127.125545,0,0,0,0,1,NaN,암사2동,강동구,29
75,75,(주)경기에너지,37.536485,127.126803,0,0,0,1,1,NaN,성내2동,강동구,34
76,76,둔촌충전소,37.525233,127.144409,0,0,1,1,1,NaN,둔촌2동,강동구,37

In [483]:
lpg_dataframe.drop(columns='dong_id_x', inplace=True)

In [484]:
lpg_dataframe.rename(columns={"dong_id_y" : "dong_id"}, inplace=True)

### pl dataframe에 넣기.

In [486]:
pl_dataframe

,pl_id,name,x_cor,y_cor,installed_2020,installed_2022,installed_2024,installed_2026,installed_2028,dong_id,동,자치구
0,0,남부초공영주차장,37.485041,126.922117,0,0,0,1,1,NaN,신사동,강남구
1,1,신사동제1공영주차장,37.484397,126.915444,0,0,0,1,1,NaN,신사동,강남구
2,2,압구정428,37.526842,127.027056,0,0,0,1,1,NaN,신사동,강남구
3,3,신구초교,37.523361,127.023992,0,0,0,1,1,NaN,신사동,강남구
4,4,논현초교,37.508491,127.026222,0,0,0,1,1,NaN,논현1동,강남구
6,5,삼성1동문화센터,37.514355,127.062609,0,0,0,1,1,NaN,삼성1동,강남구
7,6,탄천주차장,37.514112,127.066491,0,0,1,1,1,NaN,삼성1동,강남구
8,7,삼성로별관 부설,37.515910,127.052141,0,0,1,1,1,NaN,삼성1동,강남구
9,8,탄천,37.512890,127.069268,0,0,0,0,1,NaN,삼성1동,강남구
10,9,강남치매지원센터,37.510312,127.046378,0,0,0,1,1,NaN,삼성2동,강남구
11,10,구청 부설,37.517966,127.047061,0,0,0,0,1,NaN,삼성2동,강남구
13,11,도산대로25길32,37.497679,127.056453,0,0,0,0,0,NaN,대치4동,강남구
14,12,도곡로421,37.497679,127.056453,0,0,0,1,1,NaN,대치4동,강남구
15,13,도곡초교,37.499511,127.054464,0,0,0,0,1,NaN,대치4동,강남구
16,14,도곡로21길7,37.492593,127.038872,0,0,1,1,1,NaN,역삼1동,강남구
17,15,역삼1동문화센터,37.495374,127.033282,0,0,0,1,1,NaN,역삼1동,강남구
18,16,역삼문화공원,37.502514,127.030390,0,1,1,1,1,NaN,역삼1동,강남구
19,17,도곡로327,37.496157,127.051666,0,0,1,1,1,NaN,역삼2동,강남구
20,18,언주초교,37.486323,127.036793,0,0,0,0,0,NaN,도곡1동,강남구
21,19,논현로32길15,37.484252,127.043440,0,0,0,1,1,NaN,도곡2동,강남구
22,20,구룡산제1호,37.476067,127.067285,0,0,0,1,0,NaN,개포1동,강남구
23,21,구룡산제2호,37.476067,127.067285,0,0,1,0,1,NaN,개포1동,강남구
24,22,포이초교,37.475293,127.051416,0,0,0,0,1,NaN,개포4동,강남구
25,23,논현로22길,37.481259,127.046816,0,0,0,0,1,NaN,개포4동,강남구
26,24,개포로24길33,37.477139,127.049749,0,0,1,1,1,NaN,개포4동,강남구
27,25,일원역,37.484669,127.084056,0,0,1,1,1,NaN,일원본동,강남구
28,26,일원터널,37.482745,127.078902,0,1,1,1,1,NaN,일원본동,강남구
29,27,탄천제2호,37.493147,127.087768,0,0,0,1,1,NaN,일원1동,강남구
30,28,일원1동,37.489566,127.081793,0,0,0,1,1,NaN,일원1동,강남구
31,29,영희초교,37.492302,127.081131,0,0,0,0,1,NaN,일원1동,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...
546,333,약수동 공영주차장,37.567925,126.979982,0,0,0,0,1,NaN,명동,중구
547,334,필동 공영주차장,37.568355,126.977748,0,0,0,0,1,NaN,명동,중구
548,335,서소문삼성생명뒤 공영주차장,37.567361,126.989609,0,0,0,1,1,NaN,명동,중구
549,336,남산동 공영주차장,37.567876,126.981139,0,0,0,0,1,NaN,명동,중구
552,337,신당사거리 공영주차장,37.565313,126.995967,0,0,0,1,1,NaN,광희동,중구
553,338,신당역 공영주차장,37.563702,126.996663,0,0,0,0,1,NaN,광희동,중구
554,339,훈련원 화물대기,37.567026,127.003609,0,0,0,1,1,NaN,을지로동,중구
555,340,버티 공영주차장,37.567613,126.995732,0,0,0,0,1,NaN,을지로동,중구
556,341,중구구민회관 부설주차장,37.567643,127.005018,0,0,0,0,1,NaN,을지로동,중구
557,342,중림종합복지센터 부설주차장,37.567677,126.994011,0,0,0,0,1,NaN,을지로동,중구
558,343,충현어린이공원 공영주차장,37.565054,127.022888,0,0,0,1,1,NaN,신당5동,중구
560,344,충현 공영주차장,37.559548,126.966218,0,0,0,1,1,NaN,중림동,중구
561,345,다산아트 공영주차장,37.567444,127.016776,0,0,0,1,1,NaN,신당동,중구
562,346,신당동 공영주차장,37.562026,127.014296,0,0,1,1,1,NaN,신당동,중구
567,347,중랑초교,37.589184,127.075783,0,0,0,1,1,NaN,면목2동,중랑구
568,348,면목2동,37.587934,127.080895,0,0,0,1,1,NaN,면목2동,중랑구
569,349,중곡초교,37.574760,127.082679,0,0,0,1,1,NaN,면목4동,중랑구
570,350,용마폭포,37.573354,127.089120,0,0,0,1,1,NaN,면목4동,중랑구
571,351,면목5동,37.582961,127.080061,0,0,0,0,0,NaN,면목5동,중랑구
574,352,상봉2동,37.593049,127.084325,0,0,0,1,1,NaN,상봉2동,중랑구
575,353,중화1동,37.602749,127.081659,0,0,0,1,1,NaN,중화1동,중랑구
577,354,화랑대역,37.620090,127.086690,0,0,0,1,1,NaN,묵1동,중랑구
579,355,면일초교,37.591981,127.099374,0,0,0,0,1,NaN,망우3동,중랑구
581,356,봉화산역(남),37.616427,127.091907,0,0,0,1,1,NaN,신내2동,중랑구
582,357,봉수대,37.607077,127.092622,0,0,0,1,1,NaN,신내2동,중랑구
583,358,동원시장,37.590016,127.091944,0,0,0,1,1,NaN,면목본동,중랑구
584,359,은행나무,37.587058,127.091578,0,0,0,0,1,NaN,면목본동,중랑구
585,360,늘봄,37.589818,127.096400,0,0,0,1,1,NaN,면목3.8동,중랑구
586,361,까치공원,37.583508,127.086968,0,0,0,1,1,NaN,면목3.8동,중랑구
587,362,금란,37.599869,127.101590,0,0,0,1,0,NaN,망우본동,중랑구

In [488]:
pl_dataframe = pd.merge(pl_dataframe, dong_temp, how='left', on = ['동', '자치구'])

In [490]:
pl_dataframe.drop(columns='dong_id_x', inplace=True)

In [491]:
pl_dataframe.rename(columns={"dong_id_y" : "dong_id"}, inplace=True)

# Dataframe 객체를 SQLITE DB에 저장하기.

### LPG 데이터베이스를 변환하기.

In [492]:
import sqlite3

In [495]:
con = sqlite3.connect("DB_Data/lpg.db")

In [496]:
lpg_dataframe.to_sql('lpg', con)

In [497]:
con.close()

In [498]:
con = sqlite3.connect("DB_Data/parking_lot.db")

In [499]:
pl_dataframe.to_sql("parking_lot", con)

In [500]:
con.close()