In [2]:
import numpy as np
import pandas as pd

In [4]:
lpg = pd.read_csv("raw_Data/lpg.csv", encoding='cp949')

In [19]:
lpg.drop_duplicates(subset='업체명', inplace=True)

In [21]:
lpg

,Unnamed: 0,자치구,동,업체명,동주소,경도,위도
0,79,성동구,성수1가2동,덕마가스충전소,서울특별시 성동구 왕십리로 124,37.548711,127.042727
1,81,성동구,성수2가3동,대성산업(주)동부충전소,서울특별시 성동구 광나루로 200,37.550454,127.050193
2,93,광진구,중곡1동,현대오일뱅크 중곡동충전소,서울특별시 광진구 동일로 323,37.560049,127.071521
3,94,광진구,중곡1동,한양에너지(주),서울특별시 광진구 동일로 381,37.564958,127.074351
4,103,광진구,자양1동,해양가스,서울특별시 광진구 자양로 77,37.534588,127.081491
5,108,동대문구,휘경1동,수도에너지(주)동서울충전소,서울특별시 동대문구 망우로 57,37.589635,127.057249
6,111,동대문구,청량리동,(주)홍릉가스충전소,서울특별시 동대문구 회기로 44,37.591046,127.039042
7,117,동대문구,답십리2동,복지장안충전소,서울특별시 동대문구 한천로 169,37.576154,127.065037
8,118,동대문구,장안1동,장안동가스충전소,서울특별시 동대문구 천호대로 353,37.562897,127.056468
9,126,중랑구,면목5동,(주)풍림에너지,서울특별시 중랑구 동일로 553,37.579640,127.077050
10,131,중랑구,중화2동,동일석유(주)황금충전소,서울특별시 중랑구 망우로 209,37.594147,127.073658
11,135,중랑구,신내1동,신내LPG충전소,서울특별시 중랑구 용마산로 691,37.612708,127.098625
12,142,중랑구,망우본동,망우충전소,서울특별시 중랑구 망우로 449,37.600566,127.099727
13,152,성북구,길음2동,우일에너지(주),서울특별시 성북구 종암로 201,37.607911,127.028059
14,157,성북구,장위3동,(주)장위가스,서울특별시 성북구 화랑로 291,37.613232,127.058435
15,163,강북구,번1동,서울와사공업(주),서울특별시 강북구 도봉로 318,37.636198,127.022329
16,166,강북구,번3동,(주)청학에너지,서울특별시 강북구 한천로 833,37.628133,127.041865
17,167,강북구,수유1동,국제가스공업(주),서울특별시 강북구 덕릉로24길 6,37.634290,127.019657
21,190,도봉구,쌍문2동,케이와이에너지 (주)한영충전소,서울특별시 도봉구 도봉로 627,37.660563,127.039175
22,193,도봉구,방학1동,(주)에스케이행복에너지,서울특별시 도봉구 도봉로 690,37.665771,127.041380
23,197,도봉구,창2동,동원가스충전소,서울특별시 도봉구 도봉로 430,37.644256,127.030357
24,201,도봉구,도봉1동,(주)평안에너지 도봉충전소,서울특별시 도봉구 도봉로 983,37.666950,127.003720
25,206,노원구,공릉2동,복지공릉충전소,서울특별시 노원구 화랑로 826,37.638797,127.107360
26,212,노원구,상계1동,(주)노일가스,서울특별시 노원구 동일로 1601,37.671412,127.053361
27,213,노원구,상계1동,복지노원충전소,서울특별시 노원구 동일로 1778,37.686866,127.053645
28,221,노원구,중계2.3동,(주)평안에너지상계충전소,서울특별시 노원구 동일로210길 86,37.649171,127.064857
29,222,노원구,공릉1동,신성에너지주식회사,서울특별시 노원구 동일로 1113,37.629062,127.068660
30,223,노원구,공릉1동,태능가스(주),서울특별시 노원구 화랑로 405,37.616956,127.070336
31,234,은평구,증산동,신흥에너지산업(주),서울특별시 은평구 수색로 199,37.578588,126.898188
32,235,은평구,증산동,(주)삼표에너지 수색충전소,서울특별시 은평구 수색로 181,37.577704,126.899168
...,...,...,...,...,...,...,...
59,344,강서구,화곡1동,대흥에너지산업(주),서울특별시 강서구 곰달래로24길 19,37.529724,126.845029
60,348,구로구,구로3동,동일석유(주)남부충전소,서울특별시 구로구 시흥대로 573,37.484273,126.899764
62,359,구로구,오류2동,대성산업(주)오류동충전소,서울특별시 구로구 경인로8길 31,37.538042,126.728050
63,360,구로구,수궁동,오승프라임산업(주),서울특별시 구로구 신정로 59,37.506903,126.826906
64,362,구로구,구로2동,한일가스산업(주),서울특별시 구로구 경인로 537,37.501882,126.875666
65,363,구로구,개봉1동,개봉충전소,서울특별시 구로구 경인로 364,37.496421,126.858357
68,369,금천구,독산2동,(주)중앙에너비스 삼중가스지점,서울특별시 금천구 시흥대로 316,37.461797,126.896135
69,389,영등포구,양평1동,양평동충전소,서울특별시 영등포구 선유로 157,37.527936,126.888910
70,390,영등포구,양평2동,기린에너지,서울특별시 영등포구 선유로52길 5,37.536256,126.896764
71,410,영등포구,문래동,(주)세지,서울특별시 영등포구 선유로 37,37.517433,126.886258
73,417,동작구,사당1동,수도석유(주)방배충전소,서울특별시 서초구 동작대로 26,37.486896,126.973018
74,421,동작구,대방동,동일석유(주)동주충전소,서울특별시 동작구 상도로 74,37.499417,126.926646
75,433,관악구,낙성대동,명화가스(주),서울특별시 관악구 관악로 96,37.473676,126.951276
76,439,관악구,서림동,신림충전소,서울특별시 관악구 신림로 170,37.473539,126.931969
77,460,서초구,잠원동,(주)영동가스,서울특별시 서초구 잠원로 181,37.518893,127.009666
78,473,서초구,방배3동,서초충전소,서울특별시 서초구 남부순환로 2224,37.473066,126.993278
79,476,서초구,양재2동,(주)에이치앤디이-서울만남의광장,서울특별시 서초구 양재대로12길 73-71,37.459906,127.039871
86,489,강남구,논현2동,(주)상현상사,서울특별시 강남구 학동로 204,37.513631,127.029157
87,504,강남구,도곡1동,진양가스,서울특별시 강남구 강남대로58길 61,37.490583,127.034634
88,517,강남구,일원2동,대치에너지주식회사,서울특별시 강남구 남부순환로 3179,37.499300,127.075901
90,519,강남구,일원2동,남서울가스(주),서울특별시 강남구 남부순환로 3154,37.497780,127.073376
92,522,강남구,세곡동,강남복지충전소,서울특별시 강남구 밤고개로 200,37.476329,127.103276
93,523,강남구,세곡동,(주)수서에너지,서울특별시 강남구 밤고개로 127,37.482796,127.102826
94,541,송파구,오금동,오금가스충전소,서울특별시 송파구 마천로 103,37.506158,127.129408
95,545,송파구,석촌동,홍익에너지(주),서울특별시 송파구 석촌호수로 242,37.508105,127.101451
96,555,송파구,잠실본동,강동LPG충전소,서울특별시 송파구 삼전로 47,37.503449,127.084675
97,567,강동구,상일동,복지상일충전소,서울특별시 강동구 천호대로 1452,37.545049,127.167585
98,572,강동구,암사2동,암사충전소,서울특별시 강동구 올림픽로 791,37.551779,127.125545
99,578,강동구,성내2동,(주)경기에너지,서울특별시 강동구 천호대로 1056,37.536485,127.126803
100,581,강동구,둔촌2동,둔촌충전소,서울특별시 강동구 동남로 563,37.525233,127.144409

In [80]:
parking_lot = pd.read_csv("raw_Data/juchajang_final.csv", encoding='cp949')

In [81]:
parking_lot.drop_duplicates(subset='주차장명', inplace=True)

In [82]:
route = pd.read_excel("raw_Data/route.xlsx")

In [83]:
route.drop(columns='Unnamed: 1', inplace=True)

In [84]:
route['origin_coor'] = 0

In [85]:
route['node1_coor'] = 0

In [86]:
route['node2_coor'] = 0

In [87]:
route['node3_coor'] = 0

In [62]:
route['node1'].str.replace("")

'공항동(송정역)\xa0'

In [92]:
route['출발점'] = route['출발점'].str.replace("\xa0","")

In [97]:
for i in range(1,5):
    route['node'+str(i)] = route['node' + str(i)].str.replace("\xa0", "")

In [99]:
route.iloc[0]['node1']

'공항동(송정역)'

In [100]:
parking_lot[parking_lot['주차장명'] == route.iloc[0]['node1']]

,Unnamed: 0,주차장관리번호,주차장명,주차장구분,주차장유형,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,관리기관명,전화번호,위도,경도_x,데이터기준일자,제공기관코드,제공기관명,Unnamed: 33,도로명주소,행정구역
208,208,115-2-000005,공항동(송정역),공영,노외,11,3,미시행,평일+토요일+공휴일,00:00,...,서울시설공단,-1,37.560321,126.810614,2019-04-30,B553774,서울시설공단,-1.0,서울특별시 강서구 공항대로4길 26-4,공항동

In [76]:
for i in range(1,5):
    route['node'+str(i)] = route['node' + str(i)].str.replace("주차장", "")

In [79]:
route.iloc[0]['node2']

'명 화곡5-2'

In [88]:
route['node4_coor'] = 0

In [187]:
for i in range(len(route)):
    for j in range(len(lpg)):
            if route.iloc[i]['출발점'] == lpg.iloc[j]['업체명']:
                route.loc[i,'origin_coor'] = str([lpg.iloc[j]['경도'], lpg.iloc[j]['위도']])

In [170]:
for i in range(1,5):
    for j in range(len(route)):
        for k in range(len(parking_lot)):
            if route.iloc[j]['node'+str(i)] == parking_lot.iloc[k]['주차장명']:
                route.loc[j,'node'+str(i)+"_coor"] = [parking_lot.iloc[k]['경도_x'], parking_lot.iloc[k]['위도']]

In [172]:
route

,출발점,node1,node2,node3,node4,2022,2024,origin_coor,node1_coor,node2_coor,node3_coor,node4_coor
0,대흥에너지산업(주),공항동(송정역),화곡5-2,문래동 공영주차장,대방생태,1,0,"[37.52972379999999, 126.84502930000001]","[126.81061399999999, 37.560321]","[126.83854790000001, 37.5441769]","[126.88745300000001, 37.516205]","[126.92664099999999, 37.500189]"
1,강남복지충전소,주차장명 일원역,도곡로21길7,잠원동 방음언덕형 공영주차장,암사1동공영주차장,1,0,"[37.4763295, 127.10327609999999]","[126.95984399999999, 37.474496]","[127.0388718483, 37.4925934254]","[127.016135, 37.515762]","[127.13798500000001, 37.55275200000001]"
2,수도석유(주)방배충전소,흑석3동,동작대교,이수 주차빌딩,사당노외,0,1,"[37.4868961, 126.973018]","[126.96228700000002, 37.506417]","[126.980263, 37.505942]","[126.9853886, 37.4962412]","[126.98376299999998, 37.475302]"
3,서초충전소,방배열린 문화센터,반포4동 주민센터 공영주차장,미도아파트 앞 주차빌딩,교대역동측,0,1,"[37.4730658, 126.99327770000001]","[126.9922476, 37.4889095]","[127.0003038, 37.497432]","[127.01044399999999, 37.4999956]","[127.01597120000001, 37.4939238]"
4,(주)영동가스,언구비 주차빌딩,역삼문화공원,도곡로21길7,양재주차빌딩,0,1,"[37.5188926, 127.00966609999999]","[127.02098799999999, 37.504727]","[127.03039046159999, 37.5025141908]","[127.0388718483, 37.4925934254]","[127.041321, 37.4785659]"
5,(주)상현상사,언북초교,삼성로별관 부설,탄천주차장,아시아공원,0,1,"[37.5136307, 127.0291575]","[127.0447140682, 37.520126074000004]","[127.0521408548, 37.5159099376]","[127.066491114, 37.5141115358]","[127.07828, 37.510186]"
6,남서울가스(주),개포동공원,도곡로327,개포로24길33,청계산청룡,0,1,"[37.4977796, 127.0733765]","[127.068292231, 37.4897076707]","[127.0516657363, 37.4961565104]","[127.0497487923, 37.4771388546]","[127.05962199999999, 37.44665300000001]"
7,강남복지충전소,구룡산제2호,일원터널,일원역,수서역,0,1,"[37.4763295, 127.10327609999999]","[127.0672849458, 37.4760669787]","[127.078902, 37.482745]","[127.084056, 37.484669]","[127.09993500000002, 37.487944]"
8,오금가스충전소,방이동,더다이닝호수,서울놀이마당,NaN,0,1,"[37.5061584, 127.12940829999998]","[127.11391299999998, 37.51372]","[127.10108799999999, 37.510556]","[127.09772099999999, 37.508941]",0
9,둔촌충전소,암사1동공영주차장,가락동2(체비지),문정근린공원,NaN,0,1,"[37.5252332, 127.1444095]","[127.13798500000001, 37.55275200000001]","[127.119759, 37.494681]","[127.124748, 37.485972]",0
10,은평서부충전소,갈현1동 공영주차장,새장골 공영주차장,비봉,NaN,0,1,"[37.6436336, 126.91902420000001]","[126.91533700000001, 37.626498]","[126.923549, 37.624469]","[126.9565401309, 37.612215534899995]",0
11,(주)삼표에너지 수색충전소,서신초교지하공영주차장,응암3동 공영주차장,매바위공영주차장,NaN,0,1,"[37.577704499999996, 126.8991679]","[126.90683899999999, 37.59231079999999]","[126.91528899999999, 37.593506]","[126.920786, 37.586576]",0
12,강서가스충전소,천왕역,다락골,화곡5-2,화곡6-1,0,1,"[37.5549768, 126.76673799999999]","[126.83888999999999, 37.4866]","[126.849601, 37.516131]","[126.83854790000001, 37.5441769]","[126.84626609999998, 37.5529786]"
13,대영가스 충전소,화곡본-2,달마을,양평2동청사 공영주차장,당산1동 공영주차장,0,1,"[37.565115899999995, 126.80653889999999]","[126.84855309999999, 37.5441208]","[126.871574, 37.544424]","[126.885352, 37.536396]","[126.899427, 37.523768]"
14,대흥에너지산업(주),밝은빛,어울림,목동타운홀,목3동 해운,0,1,"[37.52972379999999, 126.84502930000001]","[126.861236, 37.516217]","[126.869307, 37.522152]","[126.876896, 37.532877]","[126.86511100000001, 37.5419998]"
15,(주)세지,영등포동제2 공영주차장,신길환승(5호선)공영주차장,신길1동공영주차장,영등포본동제1 공영주차장,0,1,"[37.517433399999994, 126.88625829999998]","[126.908556, 37.523736]","[126.91466299999999, 37.517666]","[126.918608, 37.510226]","[126.909151, 37.514358]"
16,동일석유(주)남부충전소,가산동,독산1동,하늘공원 주차장,대림운동장공영주차장,0,1,"[37.4842727, 126.89976419999999]","[126.8955605, 37.4766272]","[126.8947892, 37.4648929]","[126.880518, 37.487394]","[126.89481, 37.499611]"
17,동일석유(주)동주충전소,신대방역,대림3동공영주차장,신길6동공영주차장,도화,0,1,"[37.4994173, 126.9266463]","[126.913219, 37.48755900000001]","[126.900465, 37.497991]","[126.91133700000002, 37.50262100000001]","[126.934969, 37.49962100000001]"

In [109]:
lpg[lpg['업체명'] == '동일석유(주)남부충전소']

,Unnamed: 0,자치구,동,업체명,동주소,경도,위도
60,348,구로구,구로3동,동일석유(주)남부충전소,서울특별시 구로구 시흥대로 573,37.484273,126.899764

In [135]:
route.loc[16, '출발점'] = '동일석유(주)남부충전소'

In [139]:
route.loc[16,'origin_coor'] =   str([37.484273, 126.899764])

In [121]:
lpg[lpg['업체명'] == '동일석유(주)남부충전소']['경도']

60    37.484273
Name: 경도, dtype: float64

In [122]:
lpg[lpg['업체명'] == '동일석유(주)남부충전소']['위도']

60    126.899764
Name: 위도, dtype: float64

In [134]:
lpg[lpg['업체명'] == '동일석유(주)동주충전소']

,Unnamed: 0,자치구,동,업체명,동주소,경도,위도
74,421,동작구,대방동,동일석유(주)동주충전소,서울특별시 동작구 상도로 74,37.499417,126.926646

In [136]:
route.loc[17, '출발점'] = '동일석유(주)동주충전소'

In [140]:
route.loc[17,'origin_coor'] =   str([37.499417, 126.926646])

In [143]:
parking_lot[parking_lot['주차장명'] == '명천왕역']

Empty DataFrame
Columns: [Unnamed: 0, 주차장관리번호, 주차장명, 주차장구분, 주차장유형, 주차구획수, 급지구분, 부제시행구분, 운영요일, 평일운영시작시각, 평일운영종료시각, 토요일운영시작시각, 토요일운영종료시각, 공휴일운영시작시각, 공휴일운영종료시각, 요금정보, 주차기본시간, 주차기본요금, 추가단위시간, 추가단위요금, 1일주차권요금적용시간, 1일주차권요금, 월정기권요금, 결제방법, 특기사항, 관리기관명, 전화번호, 위도, 경도_x, 데이터기준일자, 제공기관코드, 제공기관명, Unnamed: 33, 도로명주소, 행정구역]
Index: []

[0 rows x 35 columns]

In [144]:
parking_lot[parking_lot['주차장명'].str.contains("왕역")]

,Unnamed: 0,주차장관리번호,주차장명,주차장구분,주차장유형,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,관리기관명,전화번호,위도,경도_x,데이터기준일자,제공기관코드,제공기관명,Unnamed: 33,도로명주소,행정구역
302,304,116-2-000002,천왕역,공영,노외,330,4,미시행,평일+토요일+공휴일,00:00,...,서울시설공단,02-2060-5026,37.4866,126.83889,2019-04-30,B553774,서울시설공단,-1.0,서울특별시 구로구 오리로 1154,오류제2동

In [148]:
route.loc[12, 'node1'] = '천왕역'

In [150]:
route.loc[12,'node1_coor'] =   str([37.4866, 126.83889])

In [157]:
route.loc[0, 'node2'] = route.iloc[0]['node2'].replace("주차장명 ", "")

In [159]:
parking_lot[parking_lot['주차장명'] == '화곡5-2']

,Unnamed: 0,주차장관리번호,주차장명,주차장구분,주차장유형,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,관리기관명,전화번호,위도,경도_x,데이터기준일자,제공기관코드,제공기관명,Unnamed: 33,도로명주소,행정구역
4,4,115-2-000006,화곡5-2,공영,노외,25,5,미시행,평일,09:00,...,서울특별시 강서구청,02-2604-8688,37.544177,126.838548,2019-03-28,3150000,서울특별시 강서구,-1.0,서울특별시 강서구 강서로 200,우장산동

In [161]:
route.loc[0, 'node2_coor'] = str([37.544177, 126.838548])

In [160]:
route.

출발점                                         대흥에너지산업(주)
node1                                         공항동(송정역)
node2                                            화곡5-2
node3                                        문래동 공영주차장
node4                                             대방생태
2022                                                 1
2024                                                 0
origin_coor    [37.52972379999999, 126.84502930000001]
node1_coor             [126.81061399999999, 37.560321]
node2_coor                                           0
node3_coor             [126.88745300000001, 37.516205]
node4_coor             [126.92664099999999, 37.500189]
Name: 0, dtype: object

In [164]:
route.loc[1, 'node2'] = '도곡로21길7'

In [166]:
parking_lot[parking_lot['주차장명'] == '도곡로21길7']

,Unnamed: 0,주차장관리번호,주차장명,주차장구분,주차장유형,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,관리기관명,전화번호,위도,경도_x,데이터기준일자,제공기관코드,제공기관명,Unnamed: 33,도로명주소,행정구역
114,114,122-2-000003,도곡로21길7,공영,노외,78,1,요일제,평일+토요일+공휴일,00:00,...,강남구도시관리공단,1544-3113,37.492593,127.038872,2019-03-05,3220000,서울특별시 강남구,-1.0,서울특별시 강남구 도곡로21길 7,역삼1동

In [167]:
route.loc[1, 'node2_coor'] = str([37.492593, 127.038872])

In [173]:
route['path_coor'] = 0

In [174]:
route

,출발점,node1,node2,node3,node4,2022,2024,origin_coor,node1_coor,node2_coor,node3_coor,node4_coor,path_coor
0,대흥에너지산업(주),공항동(송정역),화곡5-2,문래동 공영주차장,대방생태,1,0,"[37.52972379999999, 126.84502930000001]","[126.81061399999999, 37.560321]","[126.83854790000001, 37.5441769]","[126.88745300000001, 37.516205]","[126.92664099999999, 37.500189]",0
1,강남복지충전소,주차장명 일원역,도곡로21길7,잠원동 방음언덕형 공영주차장,암사1동공영주차장,1,0,"[37.4763295, 127.10327609999999]","[126.95984399999999, 37.474496]","[127.0388718483, 37.4925934254]","[127.016135, 37.515762]","[127.13798500000001, 37.55275200000001]",0
2,수도석유(주)방배충전소,흑석3동,동작대교,이수 주차빌딩,사당노외,0,1,"[37.4868961, 126.973018]","[126.96228700000002, 37.506417]","[126.980263, 37.505942]","[126.9853886, 37.4962412]","[126.98376299999998, 37.475302]",0
3,서초충전소,방배열린 문화센터,반포4동 주민센터 공영주차장,미도아파트 앞 주차빌딩,교대역동측,0,1,"[37.4730658, 126.99327770000001]","[126.9922476, 37.4889095]","[127.0003038, 37.497432]","[127.01044399999999, 37.4999956]","[127.01597120000001, 37.4939238]",0
4,(주)영동가스,언구비 주차빌딩,역삼문화공원,도곡로21길7,양재주차빌딩,0,1,"[37.5188926, 127.00966609999999]","[127.02098799999999, 37.504727]","[127.03039046159999, 37.5025141908]","[127.0388718483, 37.4925934254]","[127.041321, 37.4785659]",0
5,(주)상현상사,언북초교,삼성로별관 부설,탄천주차장,아시아공원,0,1,"[37.5136307, 127.0291575]","[127.0447140682, 37.520126074000004]","[127.0521408548, 37.5159099376]","[127.066491114, 37.5141115358]","[127.07828, 37.510186]",0
6,남서울가스(주),개포동공원,도곡로327,개포로24길33,청계산청룡,0,1,"[37.4977796, 127.0733765]","[127.068292231, 37.4897076707]","[127.0516657363, 37.4961565104]","[127.0497487923, 37.4771388546]","[127.05962199999999, 37.44665300000001]",0
7,강남복지충전소,구룡산제2호,일원터널,일원역,수서역,0,1,"[37.4763295, 127.10327609999999]","[127.0672849458, 37.4760669787]","[127.078902, 37.482745]","[127.084056, 37.484669]","[127.09993500000002, 37.487944]",0
8,오금가스충전소,방이동,더다이닝호수,서울놀이마당,NaN,0,1,"[37.5061584, 127.12940829999998]","[127.11391299999998, 37.51372]","[127.10108799999999, 37.510556]","[127.09772099999999, 37.508941]",0,0
9,둔촌충전소,암사1동공영주차장,가락동2(체비지),문정근린공원,NaN,0,1,"[37.5252332, 127.1444095]","[127.13798500000001, 37.55275200000001]","[127.119759, 37.494681]","[127.124748, 37.485972]",0,0
10,은평서부충전소,갈현1동 공영주차장,새장골 공영주차장,비봉,NaN,0,1,"[37.6436336, 126.91902420000001]","[126.91533700000001, 37.626498]","[126.923549, 37.624469]","[126.9565401309, 37.612215534899995]",0,0
11,(주)삼표에너지 수색충전소,서신초교지하공영주차장,응암3동 공영주차장,매바위공영주차장,NaN,0,1,"[37.577704499999996, 126.8991679]","[126.90683899999999, 37.59231079999999]","[126.91528899999999, 37.593506]","[126.920786, 37.586576]",0,0
12,강서가스충전소,천왕역,다락골,화곡5-2,화곡6-1,0,1,"[37.5549768, 126.76673799999999]","[126.83888999999999, 37.4866]","[126.849601, 37.516131]","[126.83854790000001, 37.5441769]","[126.84626609999998, 37.5529786]",0
13,대영가스 충전소,화곡본-2,달마을,양평2동청사 공영주차장,당산1동 공영주차장,0,1,"[37.565115899999995, 126.80653889999999]","[126.84855309999999, 37.5441208]","[126.871574, 37.544424]","[126.885352, 37.536396]","[126.899427, 37.523768]",0
14,대흥에너지산업(주),밝은빛,어울림,목동타운홀,목3동 해운,0,1,"[37.52972379999999, 126.84502930000001]","[126.861236, 37.516217]","[126.869307, 37.522152]","[126.876896, 37.532877]","[126.86511100000001, 37.5419998]",0
15,(주)세지,영등포동제2 공영주차장,신길환승(5호선)공영주차장,신길1동공영주차장,영등포본동제1 공영주차장,0,1,"[37.517433399999994, 126.88625829999998]","[126.908556, 37.523736]","[126.91466299999999, 37.517666]","[126.918608, 37.510226]","[126.909151, 37.514358]",0
16,동일석유(주)남부충전소,가산동,독산1동,하늘공원 주차장,대림운동장공영주차장,0,1,"[37.4842727, 126.89976419999999]","[126.8955605, 37.4766272]","[126.8947892, 37.4648929]","[126.880518, 37.487394]","[126.89481, 37.499611]",0
17,동일석유(주)동주충전소,신대방역,대림3동공영주차장,신길6동공영주차장,도화,0,1,"[37.4994173, 126.9266463]","[126.913219, 37.48755900000001]","[126.900465, 37.497991]","[126.91133700000002, 37.50262100000001]","[126.934969, 37.49962100000001]",0

In [201]:
for i in range(len(route)):
    path = [route.iloc[i]['origin_coor']]
    path[0] = path[0].replace("''", "")
    for j in range(1,5):
        cor = route.iloc[j]["node"+str(j)+"_coor"]
        cor.replace("''", "")
        path.append(cor)
    route.loc[i, 'path_coor'] = str(path)
    print(path)

['[37.52972379999999, 126.84502930000001]']
['[37.52972379999999, 126.84502930000001]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4763295, 127.10327609999999]']
['[37.4763295, 127.10327609999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4868961, 126.973018]']
['[37.4868961, 126.973018]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4730658, 126.99327770000001]']
['[37.4730658, 126.99327770000001]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.5188926, 127.00966609999999]']
['[37.5188926, 127.00966609999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.5136307, 127.0291575]']
['[37.5136307, 127.0291575]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4977796, 127.0733765]']
['[37.4977796, 127.0733765]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4763295, 127.10327609999999]']
['[37.4763295, 127.10327609999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.5061584, 127.12940829999998]']
['[37.5061584, 127.12940829999998]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.5252332, 127.1444095]']
['[37.5252332, 127.1444095]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.6436336, 126.91902420000001]']
['[37.6436336, 126.91902420000001]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.577704499999996, 126.8991679]']
['[37.577704499999996, 126.8991679]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.5549768, 126.76673799999999]']
['[37.5549768, 126.76673799999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.565115899999995, 126.80653889999999]']
['[37.565115899999995, 126.80653889999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.52972379999999, 126.84502930000001]']
['[37.52972379999999, 126.84502930000001]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.517433399999994, 126.88625829999998]']
['[37.517433399999994, 126.88625829999998]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4842727, 126.89976419999999]']
['[37.4842727, 126.89976419999999]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']
['[37.4994173, 126.9266463]']
['[37.4994173, 126.9266463]', '[126.95984399999999, 37.474496]', '[126.980263, 37.505942]', '[127.01044399999999, 37.4999956]', '[127.041321, 37.4785659]']

In [199]:
route.to_csv('route.csv', )

,출발점,node1,node2,node3,node4,2022,2024,origin_coor,node1_coor,node2_coor,node3_coor,node4_coor,path_coor
0,대흥에너지산업(주),공항동(송정역),화곡5-2,문래동 공영주차장,대방생태,1,0,"[37.52972379999999, 126.84502930000001]","[126.81061399999999, 37.560321]","[126.83854790000001, 37.5441769]","[126.88745300000001, 37.516205]","[126.92664099999999, 37.500189]","['[37.52972379999999, 126.84502930000001]', '[..."
1,강남복지충전소,주차장명 일원역,도곡로21길7,잠원동 방음언덕형 공영주차장,암사1동공영주차장,1,0,"[37.4763295, 127.10327609999999]","[126.95984399999999, 37.474496]","[127.0388718483, 37.4925934254]","[127.016135, 37.515762]","[127.13798500000001, 37.55275200000001]","['[37.4763295, 127.10327609999999]', '[126.959..."
2,수도석유(주)방배충전소,흑석3동,동작대교,이수 주차빌딩,사당노외,0,1,"[37.4868961, 126.973018]","[126.96228700000002, 37.506417]","[126.980263, 37.505942]","[126.9853886, 37.4962412]","[126.98376299999998, 37.475302]","['[37.4868961, 126.973018]', '[126.95984399999..."
3,서초충전소,방배열린 문화센터,반포4동 주민센터 공영주차장,미도아파트 앞 주차빌딩,교대역동측,0,1,"[37.4730658, 126.99327770000001]","[126.9922476, 37.4889095]","[127.0003038, 37.497432]","[127.01044399999999, 37.4999956]","[127.01597120000001, 37.4939238]","['[37.4730658, 126.99327770000001]', '[126.959..."
4,(주)영동가스,언구비 주차빌딩,역삼문화공원,도곡로21길7,양재주차빌딩,0,1,"[37.5188926, 127.00966609999999]","[127.02098799999999, 37.504727]","[127.03039046159999, 37.5025141908]","[127.0388718483, 37.4925934254]","[127.041321, 37.4785659]","['[37.5188926, 127.00966609999999]', '[126.959..."
5,(주)상현상사,언북초교,삼성로별관 부설,탄천주차장,아시아공원,0,1,"[37.5136307, 127.0291575]","[127.0447140682, 37.520126074000004]","[127.0521408548, 37.5159099376]","[127.066491114, 37.5141115358]","[127.07828, 37.510186]","['[37.5136307, 127.0291575]', '[126.9598439999..."
6,남서울가스(주),개포동공원,도곡로327,개포로24길33,청계산청룡,0,1,"[37.4977796, 127.0733765]","[127.068292231, 37.4897076707]","[127.0516657363, 37.4961565104]","[127.0497487923, 37.4771388546]","[127.05962199999999, 37.44665300000001]","['[37.4977796, 127.0733765]', '[126.9598439999..."
7,강남복지충전소,구룡산제2호,일원터널,일원역,수서역,0,1,"[37.4763295, 127.10327609999999]","[127.0672849458, 37.4760669787]","[127.078902, 37.482745]","[127.084056, 37.484669]","[127.09993500000002, 37.487944]","['[37.4763295, 127.10327609999999]', '[126.959..."
8,오금가스충전소,방이동,더다이닝호수,서울놀이마당,NaN,0,1,"[37.5061584, 127.12940829999998]","[127.11391299999998, 37.51372]","[127.10108799999999, 37.510556]","[127.09772099999999, 37.508941]",0,"['[37.5061584, 127.12940829999998]', '[126.959..."
9,둔촌충전소,암사1동공영주차장,가락동2(체비지),문정근린공원,NaN,0,1,"[37.5252332, 127.1444095]","[127.13798500000001, 37.55275200000001]","[127.119759, 37.494681]","[127.124748, 37.485972]",0,"['[37.5252332, 127.1444095]', '[126.9598439999..."
10,은평서부충전소,갈현1동 공영주차장,새장골 공영주차장,비봉,NaN,0,1,"[37.6436336, 126.91902420000001]","[126.91533700000001, 37.626498]","[126.923549, 37.624469]","[126.9565401309, 37.612215534899995]",0,"['[37.6436336, 126.91902420000001]', '[126.959..."
11,(주)삼표에너지 수색충전소,서신초교지하공영주차장,응암3동 공영주차장,매바위공영주차장,NaN,0,1,"[37.577704499999996, 126.8991679]","[126.90683899999999, 37.59231079999999]","[126.91528899999999, 37.593506]","[126.920786, 37.586576]",0,"['[37.577704499999996, 126.8991679]', '[126.95..."
12,강서가스충전소,천왕역,다락골,화곡5-2,화곡6-1,0,1,"[37.5549768, 126.76673799999999]","[126.83888999999999, 37.4866]","[126.849601, 37.516131]","[126.83854790000001, 37.5441769]","[126.84626609999998, 37.5529786]","['[37.5549768, 126.76673799999999]', '[126.959..."
13,대영가스 충전소,화곡본-2,달마을,양평2동청사 공영주차장,당산1동 공영주차장,0,1,"[37.565115899999995, 126.80653889999999]","[126.84855309999999, 37.5441208]","[126.871574, 37.544424]","[126.885352, 37.536396]","[126.899427, 37.523768]","['[37.565115899999995, 126.80653889999999]', '..."
14,대흥에너지산업(주),밝은빛,어울림,목동타운홀,목3동 해운,0,1,"[37.52972379999999, 126.84502930000001]","[126.861236, 37.516217]","[126.869307, 37.522152]","[126.876896, 37.532877]","[126.86511100000001, 37.5419998]","['[37.52972379999999, 126.84502930000001]', '[..."
15,(주)세지,영등포동제2 공영주차장,신길환승(5호선)공영주차장,신길1동공영주차장,영등포본동제1 공영주차장,0,1,"[37.517433399999994, 126.88625829999998]","[126.908556, 37.523736]","[126.91466299999999, 37.517666]","[126.918608, 37.510226]","[126.909151, 37.514358]","['[37.517433399999994, 126.88625829999998]', '..."
16,동일석유(주)남부충전소,가산동,독산1동,하늘공원 주차장,대림운동장공영주차장,0,1,"[37.4842727, 126.89976419999999]","[126.8955605, 37.4766272]","[126.8947892, 37.4648929]","[126.880518, 37.487394]","[126.89481, 37.499611]","['[37.4842727, 126.89976419999999]', '[126.959..."
17,동일석유(주)동주충전소,신대방역,대림3동공영주차장,신길6동공영주차장,도화,0,1,"[37.4994173, 126.9266463]","[126.913219, 37.48755900000001]","[126.900465, 37.497991]","[126.91133700000002, 37.50262100000001]","[126.934969, 37.49962100000001]","['[37.4994173, 126.9266463]', '[126.9598439999..."

In [202]:
route['출발점'] = route['origin_coor']

In [203]:
route['node1'] = route['node1_coor']

In [204]:
route['node2'] = route['node2_coor']

In [205]:
route['node3'] = route['node3_coor']

In [207]:
route['node4'] = route['node4_coor']

In [209]:
route.drop(columns=['node1_coor', 'node2_coor', 'node3_coor', 'node4_coor'], inplace=True)

In [211]:
route.drop(columns=['origin_coor'], inplace=True)

In [213]:
route.to_csv("DB_Data/route.csv")